export const GAME_RULES = {
  // Players
  MIN_PLAYERS: 3,
  DEFAULT_PLAYERS: 4,
  MAX_PLAYERS: 4,

  // Economy
  STARTING_BALANCE: 100,
  DOUBLE_MULTIPLIER: 2,
  WINNER_MULTIPLIER: 2,
  LOSER_MULTIPLIER: 0.5,
  DOUBLER_LOSS_MULTIPLIER: 0.25,

  // Cards
  DECK_SIZE: 24,
  CARDS_PER_PLAYER: 4,
  CARD_RANKS: ['A', 'K', 'Q', 'J', '10', '9'],
  CARDS_PER_RANK: 4,

  // Timers (seconds)
  PHASE_TIMEOUT_VIEW_CARDS: 10,
  PHASE_TIMEOUT_IN_OUT: 15,
  PHASE_TIMEOUT_DOUBLE_SELECTION: 20,
  PHASE_TIMEOUT_NEGOTIATION: 60,
  PHASE_TIMEOUT_REVEAL: 30,
  PHASE_TIMEOUT_RESULT: 15,

  // Economy
  OFFER_BUDGET_SOURCE: 'ROUND_PROFIT',
  OFFER_EXPIRATION_SECONDS: 60,
  RATE_LIMIT_OFFERS_PER_ROUND: 5,
  RATE_LIMIT_ACTIONS_PER_SECOND: 10,

  // Double Selection
  FIRST_ROUND_DOUBLE_SELECTION: 'RANDOM',
  NEXT_ROUND_DOUBLE_SELECTION: 'HIGHEST_BALANCE',

  // Edge Cases - Configurable
  AUTO_DOUBLE_ON_ALL_PASS: 'SKIP_ROUND',
  DOUBLER_ALONE_BEHAVIOR: 'WIN_AUTOMATICALLY',
  TIE_BREAKING_RULE: 'SEAT_ORDER',
  MINIMUM_BALANCE: 0,
  ELIMINATION_ON_ZERO_BALANCE: false,
  ROUNDING_POLICY: 'ROUND_HALF_UP',
  DISCONNECT_TIMEOUT_SECONDS: 30,
  AUTO_ACTION_ON_DISCONNECT: 'DEFAULT',
  DOUBLER_DISCONNECT_POLICY: 'PAUSE',
  GAME_START_TIMEOUT_MINUTES: 5,

  // Features
  ENABLE_VOICE_CHAT: true,
  ENABLE_BOT_PLAYERS: true,
  ENABLE_PRIVATE_ROOMS: true,
  ENABLE_PUBLIC_ROOMS: true,

  // Security
  RATE_LIMIT_LOGIN_ATTEMPTS: 5,
  RATE_LIMIT_LOGIN_WINDOW_MINUTES: 15,
  RATE_LIMIT_GLOBAL_PER_MINUTE: 100,
  SESSION_TIMEOUT_MINUTES: 30,
} as const;

export type GameRules = typeof GAME_RULES;
