export enum GamePhase {
  DEALING = 'DEALING',
  VIEW_CARDS = 'VIEW_CARDS',
  IN_OUT_SELECTION = 'IN_OUT_SELECTION',
  DOUBLE_SELECTION = 'DOUBLE_SELECTION',
  DOUBLE_ACCEPTED = 'DOUBLE_ACCEPTED',
  NEGOTIATION = 'NEGOTIATION',
  OFFER_PENDING = 'OFFER_PENDING',
  REQUEST_PENDING = 'REQUEST_PENDING',
  REVEAL_CONFIRMATION = 'REVEAL_CONFIRMATION',
  REVEALING = 'REVEALING',
  CALCULATING_RESULT = 'CALCULATING_RESULT',
  ROUND_RESULT = 'ROUND_RESULT',
  FINISHED = 'FINISHED',
}

export enum PlayerState {
  WAITING = 'WAITING',
  IN = 'IN',
  OUT = 'OUT',
  SPECTATOR = 'SPECTATOR',
  DOUBLER = 'DOUBLER',
  NEGOTIATING = 'NEGOTIATING',
  REVEALING = 'REVEALING',
  REVEALED = 'REVEALED',
  RESULT = 'RESULT',
  DISCONNECTED = 'DISCONNECTED',
}

export enum RoundPlayerStatus {
  IN = 'IN',
  OUT = 'OUT',
  SPECTATOR = 'SPECTATOR',
  REVEALING = 'REVEALING',
  WAITING = 'WAITING',
  DISCONNECTED = 'DISCONNECTED',
}

export enum RoomType {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
  AI = 'AI',
}

export enum RoomStatus {
  WAITING = 'WAITING',
  STARTING = 'STARTING',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
}

export enum OfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  INCREASED = 'INCREASED',
  EXPIRED = 'EXPIRED',
}

export enum EventType {
  PLAYER_CONNECTED = 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
  PLAYER_RECONNECTED = 'PLAYER_RECONNECTED',
  PLAYER_JOINED_ROOM = 'PLAYER_JOINED_ROOM',
  PLAYER_LEFT_ROOM = 'PLAYER_LEFT_ROOM',
  ROOM_STARTED = 'ROOM_STARTED',
  GAME_STARTED = 'GAME_STARTED',
  ROUND_STARTED = 'ROUND_STARTED',
  ROUND_FINISHED = 'ROUND_FINISHED',
  GAME_FINISHED = 'GAME_FINISHED',
  PHASE_CHANGED = 'PHASE_CHANGED',
  CARDS_DEALT = 'CARDS_DEALT',
  PLAYER_IN = 'PLAYER_IN',
  PLAYER_OUT = 'PLAYER_OUT',
  DOUBLE_OFFERED = 'DOUBLE_OFFERED',
  DOUBLE_ACCEPTED = 'DOUBLE_ACCEPTED',
  DOUBLE_REJECTED = 'DOUBLE_REJECTED',
  OFFER_CREATED = 'OFFER_CREATED',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_REJECTED = 'OFFER_REJECTED',
  INCREASE_REQUESTED = 'INCREASE_REQUESTED',
  INCREASE_ACCEPTED = 'INCREASE_ACCEPTED',
  INCREASE_REJECTED = 'INCREASE_REJECTED',
  PLAYER_EXITED = 'PLAYER_EXITED',
  PLAYER_REVEALED = 'PLAYER_REVEALED',
  WINNER_DETERMINED = 'WINNER_DETERMINED',
  BALANCE_UPDATED = 'BALANCE_UPDATED',
}
